### ISSUE TITLE
RAW MXF 6k plates from Sony Venice (2) not exporting. OTIO error

### ISSUE THREAD

**Issue by basvanbergen** [ynput/ayon-resolve#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When exporting a 6k (6054x3192) plate from a RAW mxf of a "Sony Venice" (2) camera, the publish hangs on "extract OTIO trim longer video"

### Expected Behavior:

being able to publish

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

- Load in a 6k MXF from a Sony Venice 2
> I've attached an example MXF (sadly I do not have any smaller sharable file)
> https://www.dropbox.com/scl/fi/1syjh9po7e58kxotjc5c0/A333C002_2409125M.mxf?rlkey=fbqszt2st0pfbrhke3j5afxtn&st=hutx2l27&dl=0
- Mark clip color: chocolate
- Create "Create Publishable Clip"
- press "Publish"

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
DEBUG: otio_trim_range: TimeRange(RationalTime(83, 25), RationalTime(63, 25))
DEBUG: self.staging_dir: C:\Users\Bas\AppData\Local\Temp\pyblish_tmp_8e_h5zve
DEBUG: input_file_path: E:\HEMA2024_Day01\ORIGINAL_MATERIAL\20240915\CAM_A\A001CL7S\Clip\A001C001_240911L8\A001C001_240911L8.mxf
DEBUG: Executing [GET] addons/ayon_third_party/1.1.1/files_info
DEBUG: http://192.168.178.184:5000 "GET /api/addons/ayon_third_party/1.1.1/files_info HTTP/1.1" 200 925
DEBUG: Response <RestApiResponse [200]>
DEBUG: Executing: C:\Users\Bas\AppData\Local\Ynput\AYON\addons\ayon_third_party_1.1.1\ayon_third_party\downloads\ffmpeg\bin\ffmpeg.exe -ss 3.32 -t 2.52 -i E:\HEMA2024_Day01\ORIGINAL_MATERIAL\20240915\CAM_A\A001CL7S\Clip\A001C001_240911L8\A001C001_240911L8.mxf -c copy C:\Users\Bas\AppData\Local\Temp\pyblish_tmp_8e_h5zve\A001C001_240911L8_trimmed.mxf
INFO: ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[mxf @ 00000271e3df06c0] could not resolve sub descriptor strong ref
[mxf @ 00000271e3df06c0] source track 2: stream 0, no descriptor found
[mxf @ 00000271e3df06c0] could not resolve sub descriptor strong ref
    Last message repeated 4 times
[mxf @ 00000271e3df06c0] Could not find codec parameters for stream 0 (Video: none, none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Guessed Channel Layout for Input Stream #0.1 : mono
Guessed Channel Layout for Input Stream #0.2 : mono
Guessed Channel Layout for Input Stream #0.3 : mono
Guessed Channel Layout for Input Stream #0.4 : mono
Input #0, mxf, from 'E:\HEMA2024_Day01\ORIGINAL_MATERIAL\20240915\CAM_A\A001CL7S\Clip\A001C001_240911L8\A001C001_240911L8.mxf':
  Metadata:
    operational_pattern_ul: 060e2b34.04010101.0d010201.01010900
    toolkit_version_num: 9.0.0.0.1
    uid             : 00d4f316-7065-11ef-9a55-0800460729f1
    generation_uid  : 00d4f320-7065-11ef-a099-0800460729f1
    company_name    : Sony
    product_name    : AXS 
    product_version_num: 3.1.0.0.1
    product_version : 3.1
    application_platform: Sony SC Platform
    product_uid     : cede1604-8280-11de-8a39-08004678031c
    modification_date: 2024-09-11T17:40:57.000000Z
    material_package_umid: 0x060A2B340101010501010D4313000000AA3D9DBC640506DC08004602170729F1
    timecode        : 08:43:23:11
  Duration: 00:00:18.36, start: 0.000000, bitrate: 1497922 kb/s
  Stream #0:0: Video: none, none, 25 tbr, 25 tbn, 25 tbc
  Stream #0:1: Audio: pcm_s24le, 48000 Hz, mono, s32 (24 bit), 1152 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
  Stream #0:2: Audio: pcm_s24le, 48000 Hz, mono, s32 (24 bit), 1152 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
  Stream #0:3: Audio: pcm_s24le, 48000 Hz, mono, s32 (24 bit), 1152 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
  Stream #0:4: Audio: pcm_s24le, 48000 Hz, mono, s32 (24 bit), 1152 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
  Stream #0:5: Data: none
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
      data_type       : vbi_vanc_smpte_436M
[mxf @ 00000271e4176fc0] there must be exactly one video stream and it must be the first one
Could not write header for output file #0 (incorrect codec parameters ?): Operation not permitted
Error initializing output stream 0:0 -- 
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
    Last message repeated 1 times

ERROR: Traceback (most recent call last):
  File "C:\Users\Bas\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\pyblish\plugin.py", line 528, in __explicit_process
    runner(*args)
  File "C:\Users\Bas\AppData\Local\Ynput\AYON\addons\core_1.0.1\ayon_core\plugins\publish\extract_otio_trimming_video.py", line 49, in process
    new_file = self._ffmpeg_trim_seqment(
  File "C:\Users\Bas\AppData\Local\Ynput\AYON\addons\core_1.0.1\ayon_core\plugins\publish\extract_otio_trimming_video.py", line 98, in _ffmpeg_trim_seqment
    output = run_subprocess(
  File "C:\Users\Bas\AppData\Local\Ynput\AYON\addons\core_1.0.1\ayon_core\lib\execute.py", line 167, in run_subprocess
    raise RuntimeError(exc_msg)
RuntimeError: Executing arguments was not successful: "(['C:\\Users\\Bas\\AppData\\Local\\Ynput\\AYON\\addons\\ayon_third_party_1.1.1\\ayon_third_party\\downloads\\ffmpeg\\bin\\ffmpeg.exe', '-ss', '3.32', '-t', '2.52', '-i', 'E:\\HEMA2024_Day01\\ORIGINAL_MATERIAL\\20240915\\CAM_A\\A001CL7S\\Clip\\A001C001_240911L8\\A001C001_240911L8.mxf', '-c', 'copy', 'C:\\Users\\Bas\\AppData\\Local\\Temp\\pyblish_tmp_8e_h5zve\\A001C001_240911L8_trimmed.mxf'],)"Error:
ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[mxf @ 00000271e3df06c0] could not resolve sub descriptor strong ref
[mxf @ 00000271e3df06c0] source track 2: stream 0, no descriptor found
[mxf @ 00000271e3df06c0] could not resolve sub descriptor strong ref
    Last message repeated 4 times
[mxf @ 00000271e3df06c0] Could not find codec parameters for stream 0 (Video: none, none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Guessed Channel Layout for Input Stream #0.1 : mono
Guessed Channel Layout for Input Stream #0.2 : mono
Guessed Channel Layout for Input Stream #0.3 : mono
Guessed Channel Layout for Input Stream #0.4 : mono
Input #0, mxf, from 'E:\HEMA2024_Day01\ORIGINAL_MATERIAL\20240915\CAM_A\A001CL7S\Clip\A001C001_240911L8\A001C001_240911L8.mxf':
  Metadata:
    operational_pattern_ul: 060e2b34.04010101.0d010201.01010900
    toolkit_version_num: 9.0.0.0.1
    uid             : 00d4f316-7065-11ef-9a55-0800460729f1
    generation_uid  : 00d4f320-7065-11ef-a099-0800460729f1
    company_name    : Sony
    product_name    : AXS 
    product_version_num: 3.1.0.0.1
    product_version : 3.1
    application_platform: Sony SC Platform
    product_uid     : cede1604-8280-11de-8a39-08004678031c
    modification_date: 2024-09-11T17:40:57.000000Z
    material_package_umid: 0x060A2B340101010501010D4313000000AA3D9DBC640506DC08004602170729F1
    timecode        : 08:43:23:11
  Duration: 00:00:18.36, start: 0.000000, bitrate: 1497922 kb/s
  Stream #0:0: Video: none, none, 25 tbr, 25 tbn, 25 tbc
  Stream #0:1: Audio: pcm_s24le, 48000 Hz, mono, s32 (24 bit), 1152 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
  Stream #0:2: Audio: pcm_s24le, 48000 Hz, mono, s32 (24 bit), 1152 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
  Stream #0:3: Audio: pcm_s24le, 48000 Hz, mono, s32 (24 bit), 1152 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
  Stream #0:4: Audio: pcm_s24le, 48000 Hz, mono, s32 (24 bit), 1152 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
  Stream #0:5: Data: none
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
      data_type       : vbi_vanc_smpte_436M
[mxf @ 00000271e4176fc0] there must be exactly one video stream and it must be the first one
Could not write header for output file #0 (incorrect codec parameters ?): Operation not permitted
Error initializing output stream 0:0 -- 
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
    Last message repeated 1 times


Traceback (most recent call last):
  File "C:\Users\Bas\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\pyblish\plugin.py", line 528, in __explicit_process
    runner(*args)
  File "C:\Users\Bas\AppData\Local\Ynput\AYON\addons\core_1.0.1\ayon_core\plugins\publish\extract_otio_trimming_video.py", line 49, in process
    new_file = self._ffmpeg_trim_seqment(
  File "C:\Users\Bas\AppData\Local\Ynput\AYON\addons\core_1.0.1\ayon_core\plugins\publish\extract_otio_trimming_video.py", line 98, in _ffmpeg_trim_seqment
    output = run_subprocess(
  File "C:\Users\Bas\AppData\Local\Ynput\AYON\addons\core_1.0.1\ayon_core\lib\execute.py", line 167, in run_subprocess
    raise RuntimeError(exc_msg)
RuntimeError: Executing arguments was not successful: "(['C:\\Users\\Bas\\AppData\\Local\\Ynput\\AYON\\addons\\ayon_third_party_1.1.1\\ayon_third_party\\downloads\\ffmpeg\\bin\\ffmpeg.exe', '-ss', '3.32', '-t', '2.52', '-i', 'E:\\HEMA2024_Day01\\ORIGINAL_MATERIAL\\20240915\\CAM_A\\A001CL7S\\Clip\\A001C001_240911L8\\A001C001_240911L8.mxf', '-c', 'copy', 'C:\\Users\\Bas\\AppData\\Local\\Temp\\pyblish_tmp_8e_h5zve\\A001C001_240911L8_trimmed.mxf'],)"Error:
ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[mxf @ 00000271e3df06c0] could not resolve sub descriptor strong ref
[mxf @ 00000271e3df06c0] source track 2: stream 0, no descriptor found
[mxf @ 00000271e3df06c0] could not resolve sub descriptor strong ref
    Last message repeated 4 times
[mxf @ 00000271e3df06c0] Could not find codec parameters for stream 0 (Video: none, none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Guessed Channel Layout for Input Stream #0.1 : mono
Guessed Channel Layout for Input Stream #0.2 : mono
Guessed Channel Layout for Input Stream #0.3 : mono
Guessed Channel Layout for Input Stream #0.4 : mono
Input #0, mxf, from 'E:\HEMA2024_Day01\ORIGINAL_MATERIAL\20240915\CAM_A\A001CL7S\Clip\A001C001_240911L8\A001C001_240911L8.mxf':
  Metadata:
    operational_pattern_ul: 060e2b34.04010101.0d010201.01010900
    toolkit_version_num: 9.0.0.0.1
    uid             : 00d4f316-7065-11ef-9a55-0800460729f1
    generation_uid  : 00d4f320-7065-11ef-a099-0800460729f1
    company_name    : Sony
    product_name    : AXS 
    product_version_num: 3.1.0.0.1
    product_version : 3.1
    application_platform: Sony SC Platform
    product_uid     : cede1604-8280-11de-8a39-08004678031c
    modification_date: 2024-09-11T17:40:57.000000Z
    material_package_umid: 0x060A2B340101010501010D4313000000AA3D9DBC640506DC08004602170729F1
    timecode        : 08:43:23:11
  Duration: 00:00:18.36, start: 0.000000, bitrate: 1497922 kb/s
  Stream #0:0: Video: none, none, 25 tbr, 25 tbn, 25 tbc
  Stream #0:1: Audio: pcm_s24le, 48000 Hz, mono, s32 (24 bit), 1152 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
  Stream #0:2: Audio: pcm_s24le, 48000 Hz, mono, s32 (24 bit), 1152 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
  Stream #0:3: Audio: pcm_s24le, 48000 Hz, mono, s32 (24 bit), 1152 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
  Stream #0:4: Audio: pcm_s24le, 48000 Hz, mono, s32 (24 bit), 1152 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
  Stream #0:5: Data: none
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
      data_type       : vbi_vanc_smpte_436M
[mxf @ 00000271e4176fc0] there must be exactly one video stream and it must be the first one
Could not write header for output file #0 (incorrect codec parameters ?): Operation not permitted
Error initializing output stream 0:0 -- 
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
    Last message repeated 1 times


Traceback (most recent call last):
  File "C:\Users\Bas\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\pyblish\plugin.py", line 528, in __explicit_process
    runner(*args)
  File "C:\Users\Bas\AppData\Local\Ynput\AYON\addons\core_1.0.1\ayon_core\plugins\publish\extract_otio_trimming_video.py", line 49, in process
    new_file = self._ffmpeg_trim_seqment(
  File "C:\Users\Bas\AppData\Local\Ynput\AYON\addons\core_1.0.1\ayon_core\plugins\publish\extract_otio_trimming_video.py", line 98, in _ffmpeg_trim_seqment
    output = run_subprocess(
  File "C:\Users\Bas\AppData\Local\Ynput\AYON\addons\core_1.0.1\ayon_core\lib\execute.py", line 167, in run_subprocess
    raise RuntimeError(exc_msg)
RuntimeError: Executing arguments was not successful: "(['C:\\Users\\Bas\\AppData\\Local\\Ynput\\AYON\\addons\\ayon_third_party_1.1.1\\ayon_third_party\\downloads\\ffmpeg\\bin\\ffmpeg.exe', '-ss', '3.32', '-t', '2.52', '-i', 'E:\\HEMA2024_Day01\\ORIGINAL_MATERIAL\\20240915\\CAM_A\\A001CL7S\\Clip\\A001C001_240911L8\\A001C001_240911L8.mxf', '-c', 'copy', 'C:\\Users\\Bas\\AppData\\Local\\Temp\\pyblish_tmp_8e_h5zve\\A001C001_240911L8_trimmed.mxf'],)"Error:
ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[mxf @ 00000271e3df06c0] could not resolve sub descriptor strong ref
[mxf @ 00000271e3df06c0] source track 2: stream 0, no descriptor found
[mxf @ 00000271e3df06c0] could not resolve sub descriptor strong ref
    Last message repeated 4 times
[mxf @ 00000271e3df06c0] Could not find codec parameters for stream 0 (Video: none, none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Guessed Channel Layout for Input Stream #0.1 : mono
Guessed Channel Layout for Input Stream #0.2 : mono
Guessed Channel Layout for Input Stream #0.3 : mono
Guessed Channel Layout for Input Stream #0.4 : mono
Input #0, mxf, from 'E:\HEMA2024_Day01\ORIGINAL_MATERIAL\20240915\CAM_A\A001CL7S\Clip\A001C001_240911L8\A001C001_240911L8.mxf':
  Metadata:
    operational_pattern_ul: 060e2b34.04010101.0d010201.01010900
    toolkit_version_num: 9.0.0.0.1
    uid             : 00d4f316-7065-11ef-9a55-0800460729f1
    generation_uid  : 00d4f320-7065-11ef-a099-0800460729f1
    company_name    : Sony
    product_name    : AXS 
    product_version_num: 3.1.0.0.1
    product_version : 3.1
    application_platform: Sony SC Platform
    product_uid     : cede1604-8280-11de-8a39-08004678031c
    modification_date: 2024-09-11T17:40:57.000000Z
    material_package_umid: 0x060A2B340101010501010D4313000000AA3D9DBC640506DC08004602170729F1
    timecode        : 08:43:23:11
  Duration: 00:00:18.36, start: 0.000000, bitrate: 1497922 kb/s
  Stream #0:0: Video: none, none, 25 tbr, 25 tbn, 25 tbc
  Stream #0:1: Audio: pcm_s24le, 48000 Hz, mono, s32 (24 bit), 1152 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
  Stream #0:2: Audio: pcm_s24le, 48000 Hz, mono, s32 (24 bit), 1152 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
  Stream #0:3: Audio: pcm_s24le, 48000 Hz, mono, s32 (24 bit), 1152 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
  Stream #0:4: Audio: pcm_s24le, 48000 Hz, mono, s32 (24 bit), 1152 kb/s
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
  Stream #0:5: Data: none
    Metadata:
      file_package_umid: 0x060A2B340101010501010D4313000000AB3D9DBC640506DC08004602170729F1
      data_type       : vbi_vanc_smpte_436M
[mxf @ 00000271e4176fc0] there must be exactly one video stream and it must be the first one
Could not write header for output file #0 (incorrect codec parameters ?): Operation not permitted
Error initializing output stream 0:0 -- 
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
    Last message repeated 1 times
```

### Additional context:

Trimming the clip using resolve (Media management > Used media and trim keeping .. frame handles) fixes the problem, so I expect it has something to do with the metadata in the RAW MXF

**Comment by jakubjezek001** [comment]
We currently do not support publishing camera raw media sources as plates. We recommend first converting all raw data to an exert sequence. These can then be ingested and published into AYON as plates. We are closing this ticket because it is not a bug but a misuse of the workflow.
