### ISSUE TITLE
Publishing clip fails on integrate: no representations to integrate

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-resolve#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When having a clip, e.g. `file_v006.mp4` and publishing it from a timeline the publishing errors on integrate with:

> Instance shot has no representations to integrate

This was also reported on the community forum: https://community.ynput.io/t/got-some-error-in-resolve/1518/3?u=bigroy

### Expected Behavior:

No errors on publishing.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Use a video file with filename `file_v006.mp4` (not sure if the filename is part of the problem though)
2. Set the clip to "Chocolate"
3. Use Create to create publishable clip
4. Publish

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
...
b'Processing Integrate Resources Path'
DEBUG:pyblish.IntegrateResourcesPath:Instance does not have `resources` and `transfers`
b'Processing Integrate Asset'
DEBUG:pyblish.IntegrateAsset:Establishing staging directory @ C:\Users\User\AppData\Local\Temp\pyblish_tmp_h5sf5u4h
DEBUG:pyblish.IntegrateAsset:Looking for matching profile for: hosts: "resolve" | product_types: "workfile" | task_names: "modeling" | task_types: "Modeling"
DEBUG:pyblish.IntegrateAsset:"workfile" not found in "product_types": ['review', 'render', 'prerender']
DEBUG:pyblish.IntegrateAsset:"resolve" not found in "hosts": ['standalonepublisher']
DEBUG:pyblish.IntegrateAsset:"resolve" not found in "hosts": ['maya']
DEBUG:pyblish.IntegrateAsset:"resolve" not found in "hosts": ['traypublisher']
DEBUG:pyblish.IntegrateAsset:"resolve" not found in "hosts": ['max']
DEBUG:pyblish.IntegrateAsset:Profile selected: {'product_types': [], 'hosts': [], 'task_types': [], 'task_names': [], 'template_name': 'default'}
DEBUG:pyblish.IntegrateAsset:Product: workfileMain
DEBUG:urllib3.connectionpool:http://localhost:5000 "POST /graphql HTTP/1.1" 200 368
DEBUG:GlobalServerAPI:Response <RestApiResponse [200]>
DEBUG:pyblish.IntegrateAsset:Prepared product: workfileMain
DEBUG:urllib3.connectionpool:http://localhost:5000 "POST /graphql HTTP/1.1" 200 105
DEBUG:GlobalServerAPI:Response <RestApiResponse [200]>
*** WRN: >>> { AnatomyRoots }: [ No matching root was found in current setting. ] 
WARNING:pyblish.IntegrateAsset:Could not find root path for remapping "ynts_char_hero_modeling_v002". This may cause issues on farm.
DEBUG:pyblish.IntegrateAsset:Source: ynts_char_hero_modeling_v002
DEBUG:pyblish.IntegrateAsset:Creating new version ...
DEBUG:pyblish.IntegrateAsset:Prepared version: v006
DEBUG:urllib3.connectionpool:http://localhost:5000 "POST /graphql HTTP/1.1" 200 112
DEBUG:GlobalServerAPI:Response <RestApiResponse [200]>
DEBUG:pyblish.IntegrateAsset:Anatomy template name: default
DEBUG:pyblish.IntegrateAsset:Anatomy template name: default
DEBUG:GlobalServerAPI:Executing [POST] projects/ayontest/operations
DEBUG:urllib3.connectionpool:http://localhost:5000 "POST /api/projects/ayontest/operations HTTP/1.1" 200 204
DEBUG:GlobalServerAPI:Response <RestApiResponse [200]>
INFO:pyblish.IntegrateAsset:Product 'workfileMain' version 6 written to database..
DEBUG:pyblish.IntegrateAsset:Integrating source files to destination ...
DEBUG:pyblish.IntegrateAsset:Checking file ... C:\Users\User\AppData\Local\Temp\pyblish_tmp_h5sf5u4h\char_hero_workfileMain.otio -> C:\projects\ayontest\asset\char_hero\publish\workfile\workfileMain\v006\ynts_char_hero_workfileMain_v006.otio
DEBUG:pyblish.IntegrateAsset:Checking file ... C:\Users\User\AppData\Local\Temp\pyblish_tmp_h5sf5u4h\char_hero_workfileMain.drp -> C:\projects\ayontest\asset\char_hero\publish\workfile\workfileMain\v006\ynts_char_hero_workfileMain_v006.drp
DEBUG:pyblish.IntegrateAsset:Copying file ... C:\Users\User\AppData\Local\Temp\pyblish_tmp_h5sf5u4h\char_hero_workfileMain.otio -> C:\projects\ayontest\asset\char_hero\publish\workfile\workfileMain\v006\ynts_char_hero_workfileMain_v006.otio
DEBUG:pyblish.IntegrateAsset:Copying file ... C:\Users\User\AppData\Local\Temp\pyblish_tmp_h5sf5u4h\char_hero_workfileMain.drp -> C:\projects\ayontest\asset\char_hero\publish\workfile\workfileMain\v006\ynts_char_hero_workfileMain_v006.drp
DEBUG:pyblish.IntegrateAsset:Backed up existing files: []
DEBUG:pyblish.IntegrateAsset:Transferred files: ['C:\\projects\\ayontest\\asset\\char_hero\\publish\\workfile\\workfileMain\\v006\\ynts_char_hero_workfileMain_v006.otio', 'C:\\projects\\ayontest\\asset\\char_hero\\publish\\workfile\\workfileMain\\v006\\ynts_char_hero_workfileMain_v006.drp']
DEBUG:pyblish.IntegrateAsset:Retrieving Representation Site Sync information ...
DEBUG:pyblish.IntegrateAsset:[{'id': '6e3a6ac8-2373-400c-8169-ef4eea483fbd', 'entity_type': 'representation', 'project_name': 'ayontest', 'operation': 'create', 'data': {'id': '6f433a8238a211efaa12b4969159e74e', 'versionId': '6f37706f38a211efadaeb4969159e74e', 'files': [{'id': '6f5f26eb38a211ef9c4ab4969159e74e', 'name': 'ynts_char_hero_workfileMain_v006.otio', 'path': '{root[work]}/ayontest/asset/char_hero/publish/workfile/workfileMain/v006/ynts_char_hero_workfileMain_v006.otio', 'size': 14708, 'hash': 'ynts_char_hero_workfileMain_v006,otio|1719945575,3429427|14708', 'hash_type': 'op3'}], 'name': 'otio', 'data': {'context': {'root': {'work': 'C:/projects'}, 'project': {'name': 'ayontest', 'code': 'ynts'}, 'hierarchy': 'asset', 'folder': {'name': 'char_hero', 'type': 'Asset', 'path': '/asset/char_hero'}, 'product': {'name': 'workfileMain', 'type': 'workfile'}, 'version': 6, 'ext': 'otio', 'asset': 'char_hero', 'task': {'name': 'modeling', 'type': 'Modeling', 'short': 'mdl'}, 'subset': 'workfileMain', 'family': 'workfile', 'representation': 'otio', 'username': 'admin', 'user': 'admin'}}, 'attrib': {'path': 'C:\\projects\\ayontest\\asset\\char_hero\\publish\\workfile\\workfileMain\\v006\\ynts_char_hero_workfileMain_v006.otio', 'template': '{root[work]}/{project[name]}/{hierarchy}/{folder[name]}/publish/{product[type]}/{product[name]}/v{version:0>3}/{project[code]}_{folder[name]}_{product[name]}_v{version:0>3}<_{output}><.{frame:0>4}><_{udim}>.{ext}'}}}, {'id': '8a39085c-0711-4344-b5d8-1af6ad8aa475', 'entity_type': 'representation', 'project_name': 'ayontest', 'operation': 'create', 'data': {'id': '6f43889338a211ef899cb4969159e74e', 'versionId': '6f37706f38a211efadaeb4969159e74e', 'files': [{'id': '6f5f4dd838a211ef9555b4969159e74e', 'name': 'ynts_char_hero_workfileMain_v006.drp', 'path': '{root[work]}/ayontest/asset/char_hero/publish/workfile/workfileMain/v006/ynts_char_hero_workfileMain_v006.drp', 'size': 40172, 'hash': 'ynts_char_hero_workfileMain_v006,drp|1719945576,3212795|40172', 'hash_type': 'op3'}], 'name': 'drp', 'data': {'context': {'root': {'work': 'C:/projects'}, 'project': {'name': 'ayontest', 'code': 'ynts'}, 'hierarchy': 'asset', 'folder': {'name': 'char_hero', 'type': 'Asset', 'path': '/asset/char_hero'}, 'product': {'name': 'workfileMain', 'type': 'workfile'}, 'version': 6, 'ext': 'drp', 'asset': 'char_hero', 'task': {'name': 'modeling', 'type': 'Modeling', 'short': 'mdl'}, 'subset': 'workfileMain', 'family': 'workfile', 'representation': 'drp', 'username': 'admin', 'user': 'admin'}}, 'attrib': {'path': 'C:\\projects\\ayontest\\asset\\char_hero\\publish\\workfile\\workfileMain\\v006\\ynts_char_hero_workfileMain_v006.drp', 'template': '{root[work]}/{project[name]}/{hierarchy}/{folder[name]}/publish/{product[type]}/{product[name]}/v{version:0>3}/{project[code]}_{folder[name]}_{product[name]}_v{version:0>3}<_{output}><.{frame:0>4}><_{udim}>.{ext}'}}}]
DEBUG:GlobalServerAPI:Executing [POST] projects/ayontest/operations
DEBUG:urllib3.connectionpool:http://localhost:5000 "POST /api/projects/ayontest/operations HTTP/1.1" 200 391
DEBUG:GlobalServerAPI:Response <RestApiResponse [200]>
INFO:pyblish.IntegrateAsset:Registered 2 representations: otio, drp
b'Processing Integrate Asset'
DEBUG:pyblish.IntegrateAsset:/shots/sq01/Video_1sq01sh010_plateVideo_1 is missing reference to staging directory. Will try to get it from representation.
DEBUG:pyblish.IntegrateAsset:Looking for matching profile for: hosts: "resolve" | product_types: "plate" | task_names: "modeling" | task_types: "Modeling"
DEBUG:pyblish.IntegrateAsset:"plate" not found in "product_types": ['review', 'render', 'prerender']
DEBUG:pyblish.IntegrateAsset:"resolve" not found in "hosts": ['standalonepublisher']
DEBUG:pyblish.IntegrateAsset:"resolve" not found in "hosts": ['maya']
DEBUG:pyblish.IntegrateAsset:"resolve" not found in "hosts": ['traypublisher']
DEBUG:pyblish.IntegrateAsset:"resolve" not found in "hosts": ['max']
DEBUG:pyblish.IntegrateAsset:Profile selected: {'product_types': [], 'hosts': [], 'task_types': [], 'task_names': [], 'template_name': 'default'}
DEBUG:pyblish.IntegrateAsset:Product: plateVideo_1
DEBUG:urllib3.connectionpool:http://localhost:5000 "POST /graphql HTTP/1.1" 200 105
DEBUG:GlobalServerAPI:Response <RestApiResponse [200]>
INFO:pyblish.IntegrateAsset:Product 'plateVideo_1' not found, creating ...
DEBUG:pyblish.IntegrateAsset:Prepared product: plateVideo_1
DEBUG:urllib3.connectionpool:http://localhost:5000 "POST /graphql HTTP/1.1" 200 105
DEBUG:GlobalServerAPI:Response <RestApiResponse [200]>
*** WRN: >>> { AnatomyRoots }: [ No matching root was found in current setting. ] 
WARNING:pyblish.IntegrateAsset:Could not find root path for remapping "ynts_char_hero_modeling_v002". This may cause issues on farm.
DEBUG:pyblish.IntegrateAsset:Source: ynts_char_hero_modeling_v002
DEBUG:pyblish.IntegrateAsset:Creating new version ...
DEBUG:pyblish.IntegrateAsset:Prepared version: v001
DEBUG:urllib3.connectionpool:http://localhost:5000 "POST /graphql HTTP/1.1" 200 112
DEBUG:GlobalServerAPI:Response <RestApiResponse [200]>
DEBUG:pyblish.IntegrateAsset:Anatomy template name: default
DEBUG:GlobalServerAPI:Executing [POST] projects/ayontest/operations
DEBUG:urllib3.connectionpool:http://localhost:5000 "POST /api/projects/ayontest/operations HTTP/1.1" 200 377
DEBUG:GlobalServerAPI:Response <RestApiResponse [200]>
INFO:pyblish.IntegrateAsset:Product 'plateVideo_1' version 1 written to database..
DEBUG:pyblish.IntegrateAsset:Integrating source files to destination ...
DEBUG:pyblish.IntegrateAsset:Checking file ... C:\Users\User\Downloads\AE4_DOOH_01_renderLightingMain_v006.mp4 -> C:\projects\ayontest\shots\sq01\Video_1sq01sh010\publish\plate\plateVideo_1\v001\ynts_Video_1sq01sh010_plateVideo_1_v001.mp4
DEBUG:pyblish.IntegrateAsset:Copying file ... C:\Users\User\Downloads\AE4_DOOH_01_renderLightingMain_v006.mp4 -> C:\projects\ayontest\shots\sq01\Video_1sq01sh010\publish\plate\plateVideo_1\v001\ynts_Video_1sq01sh010_plateVideo_1_v001.mp4
DEBUG:pyblish.IntegrateAsset:Backed up existing files: []
DEBUG:pyblish.IntegrateAsset:Transferred files: ['C:\\projects\\ayontest\\shots\\sq01\\Video_1sq01sh010\\publish\\plate\\plateVideo_1\\v001\\ynts_Video_1sq01sh010_plateVideo_1_v001.mp4']
DEBUG:pyblish.IntegrateAsset:Retrieving Representation Site Sync information ...
DEBUG:pyblish.IntegrateAsset:[{'id': 'b987eb6c-a394-48d2-a265-3e493c8131ea', 'entity_type': 'representation', 'project_name': 'ayontest', 'operation': 'create', 'data': {'id': '6f9a1e3d38a211efa287b4969159e74e', 'versionId': '6f8e5df438a211efa857b4969159e74e', 'files': [{'id': '6fab238338a211ef8443b4969159e74e', 'name': 'ynts_Video_1sq01sh010_plateVideo_1_v001.mp4', 'path': '{root[work]}/ayontest/shots/sq01/Video_1sq01sh010/publish/plate/plateVideo_1/v001/ynts_Video_1sq01sh010_plateVideo_1_v001.mp4', 'size': 6850263, 'hash': 'ynts_Video_1sq01sh010_plateVideo_1_v001,mp4|1719484444,7022066|6850263', 'hash_type': 'op3'}], 'name': 'mp4', 'data': {'context': {'root': {'work': 'C:/projects'}, 'project': {'name': 'ayontest', 'code': 'ynts'}, 'hierarchy': 'shots/sq01', 'folder': {'name': 'Video_1sq01sh010', 'type': 'Shot', 'path': '/shots/sq01/Video_1sq01sh010'}, 'product': {'name': 'plateVideo_1', 'type': 'plate'}, 'version': 1, 'ext': 'mp4', 'asset': 'Video_1sq01sh010', 'task': {'name': 'modeling', 'type': 'Modeling', 'short': 'mdl'}, 'subset': 'plateVideo_1', 'family': 'plate', 'representation': 'mp4', 'username': 'admin', 'user': 'admin'}}, 'attrib': {'path': 'C:\\projects\\ayontest\\shots\\sq01\\Video_1sq01sh010\\publish\\plate\\plateVideo_1\\v001\\ynts_Video_1sq01sh010_plateVideo_1_v001.mp4', 'template': '{root[work]}/{project[name]}/{hierarchy}/{folder[name]}/publish/{product[type]}/{product[name]}/v{version:0>3}/{project[code]}_{folder[name]}_{product[name]}_v{version:0>3}<_{output}><.{frame:0>4}><_{udim}>.{ext}'}}}]
DEBUG:GlobalServerAPI:Executing [POST] projects/ayontest/operations
DEBUG:urllib3.connectionpool:http://localhost:5000 "POST /api/projects/ayontest/operations HTTP/1.1" 200 211
DEBUG:GlobalServerAPI:Response <RestApiResponse [200]>
INFO:pyblish.IntegrateAsset:Registered 1 representations: mp4
b'Processing Integrate Asset'
ERROR:pyblish.plugin:Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Ynput\AYON\dependency_packages\ayon_2403061937_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "E:\dev\ayon-core\client\ayon_core\plugins\publish\integrate.py", line 144, in process
  File "E:\dev\ayon-core\client\ayon_core\plugins\publish\integrate.py", line 182, in filter_representations
ayon_core.pipeline.publish.publish_plugins.KnownPublishError: Instance shot has no representations to integrate
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Ynput\AYON\dependency_packages\ayon_2403061937_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "<string>", line 144, in process
  File "<string>", line 182, in filter_representations
ayon_core.pipeline.publish.publish_plugins.KnownPublishError: Instance shot has no representations to integrate
```

**Comment by BigRoy** [comment]
Note that even though it fails - it does seem to have integrated the plates at least.
